GET http://localhost:3000/api/users/profile/17
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJ1c2VybmFtZSI6ImJyIiwidHlwZSI6ImFkbWluIiwiaWF0IjoxNjczOTY5MTEwLCJleHAiOjE2NzM5ODM1MTB9.a0j8jST1PhLGTO9OG9uKbB7W12r_YZdArIxyuyxktAc
refreshtoken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJ1c2VybmFtZSI6ImJyIiwidHlwZSI6ImFkbWluIiwiaWF0IjoxNjczOTY5MTEwfQ.W42wL1Z-XYRRh0AcOERQv19oGgU-S0aCts6p1icfibM
###

GET {{hostname}}api/notification/98410312-a4b4-4a6a-b048-2752b8210e23
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk4NDEwMzEyLWE0YjQtNGE2YS1iMDQ4LTI3NTJiODIxMGUyMyIsInVzZXJuYW1lIjoiYWRtIiwidHlwZSI6ImFkbWluIiwiaWF0IjoxNjc0NjUwNzY5LCJleHAiOjE2NzQ2NjUxNjl9.kdBaYDPSJWxQJmd4ctG0k_EfClRoJ11Wi5-Mxw_A0bQ
refreshtoken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk4NDEwMzEyLWE0YjQtNGE2YS1iMDQ4LTI3NTJiODIxMGUyMyIsInVzZXJuYW1lIjoiYWRtIiwidHlwZSI6ImFkbWluIiwiaWF0IjoxNjc0NjUwNzY5fQ.YetuQ0ih6VBp7ph4EXJBb29J-KrzXaln83JdyfNgTZQ

###
PUT {{hostname}}api/notification/98410312-a4b4-4a6a-b048-2752b8210e23
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk4NDEwMzEyLWE0YjQtNGE2YS1iMDQ4LTI3NTJiODIxMGUyMyIsInVzZXJuYW1lIjoiYWRtIiwidHlwZSI6ImFkbWluIiwiaWF0IjoxNjc0NjUwNzY5LCJleHAiOjE2NzQ2NjUxNjl9.kdBaYDPSJWxQJmd4ctG0k_EfClRoJ11Wi5-Mxw_A0bQ
refreshtoken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk4NDEwMzEyLWE0YjQtNGE2YS1iMDQ4LTI3NTJiODIxMGUyMyIsInVzZXJuYW1lIjoiYWRtIiwidHlwZSI6ImFkbWluIiwiaWF0IjoxNjc0NjUwNzY5fQ.YetuQ0ih6VBp7ph4EXJBb29J-KrzXaln83JdyfNgTZQ

###
PUT {{hostname}}api/cursos/adm/1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk4NDEwMzEyLWE0YjQtNGE2YS1iMDQ4LTI3NTJiODIxMGUyMyIsInVzZXJuYW1lIjoiYWRtIiwidHlwZSI6ImFkbWluIiwiaWF0IjoxNjc0NjUwNzY5LCJleHAiOjE2NzQ2NjUxNjl9.kdBaYDPSJWxQJmd4ctG0k_EfClRoJ11Wi5-Mxw_A0bQ
refreshtoken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk4NDEwMzEyLWE0YjQtNGE2YS1iMDQ4LTI3NTJiODIxMGUyMyIsInVzZXJuYW1lIjoiYWRtIiwidHlwZSI6ImFkbWluIiwiaWF0IjoxNjc0NjUwNzY5fQ.YetuQ0ih6VBp7ph4EXJBb29J-KrzXaln83JdyfNgTZQ
content-type: application/json

{
    "id": "98410312-a4b4-4a6a-b048-2752b8210e23", 
    "state": "Inativo"
}

###
PUT {{hostname}}api/videos/adm/98410312-a4b4-4a6a-b048-2752b8210e23
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk4NDEwMzEyLWE0YjQtNGE2YS1iMDQ4LTI3NTJiODIxMGUyMyIsInVzZXJuYW1lIjoiYWRtIiwidHlwZSI6ImFkbWluIiwiaWF0IjoxNjc0NzQwNDQ0LCJleHAiOjE2NzQ3NTQ4NDR9.BaEt4kDLb61IuuqU931IfFId6LdeL-UnQjGQYnMi5rU
refreshtoken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk4NDEwMzEyLWE0YjQtNGE2YS1iMDQ4LTI3NTJiODIxMGUyMyIsInVzZXJuYW1lIjoiYWRtIiwidHlwZSI6ImFkbWluIiwiaWF0IjoxNjc0NzQwNDQ0fQ.Neh4N-oUmTxP5HOlID4ooIBVfjRWmpBWLF17HzgYdmc
content-type: application/json

{
    "id": "1", 
    "id_course": "8",
    "state": "Inativo"
}

###
POST {{hostname}}api/auth/login
content-type: application/json  

{     
    "username": "julinho",     
    "password": "1323" 
}
###
POST {{hostname}}api/users/
content-type: application/json  

{     
    "username": "julinho",     
    "password": "123" ,
    "name": "julio",
    "email": "julio@gmail.com",
    "description": "eu sou o julio",
    "image": "imagem do julio"

}
